#!/bin/bash

jq -r '{
  timestamp: .timestamp | todate,
  source,
  log_level: .log_level | ascii_upcase,
  message, loc: [.file, .lineno | tostring] | join(":"),
  description: .data.description,
  stack_trace: (
    if .data.stack_trace then
      .data.stack_trace | join("\n ")
    else
      ""
    end
  ),
} | join(" - ")'
